### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by janvanhelvoort** [50ButtonsEach/flichub-sdk-web#1]
Hello,

How can I use this?

You write: `Make sure that the status of your Flic Hub is "Up and running" and that its URL is pointed towards this destination. Then press your Flic to test it.`,
The hub is up and running, but where do i need to change the url, i have the url of the hub, but with port do I need to use?

Thank you.

**Comment by Emill** [comment]
Oh. Sorry to disappoint you but this repo is some old stuff we tested a year ago that has nothing to do with the current Flic hub. I'll remove the repo to avoid confusion...
